plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.39'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation files(customgun_neo_local)

    // LuaJ
    compileOnly "${luaj_figuramc_core}"
    compileOnly "${luaj_figuramc_jse}"
    compileOnly "${luaj_bcel}"
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}